version: '3'

services:
  api:
    build: .
    image: using-flask/api:1.0
    restart: always
    ports:
      - "8080:8080"
    container_name: api
    hostname: api
    networks:
     - my_networks

networks:
  my_networks:
